### ISSUE TITLE
ModuleNotFoundError: No module named 'unit_scaling.core'

### ISSUE THREAD

**Issue by alxndrTL** [graphcore-research/unit-scaling#60]
Hello, first of all thank you for your work and for sharing the code for u-muP !

When installing the library with `pip install git+https://github.com/graphcore-research/unit-scaling.git`, running the demo yeilds the following error when importing `import unit_scaling as uu` :

```ModuleNotFoundError: No module named 'unit_scaling.core'```

Eventually I just cloned the repo and worked from there so it's not that big of a deal

**Comment by DouglasOrr** [comment]
Hi @alxndrTL, thank you very much for reporting this issue. I've hopefully fixed it now on `main`: a basic setup.py omission (the bigger problem being that I'd never tested it outside of a development environment). I'm glad you managed to work around, and hope that it didn't cost you too much time.

**Comment by alxndrTL** [comment]
Yes I just tested and it works just fine now, thank you!
