### ISSUE TITLE
`Conv1d` isn't made visible

### ISSUE THREAD

**Issue by EIFY** [graphcore-research/unit-scaling#69]
I just noticed that `Conv1d` isn't made visible in https://github.com/graphcore-research/unit-scaling/pull/67
So for now one needs to e.g.
```python
from unit_scaling._modules import Conv1d
```
instead of
```python
import unit_scaling as uu
# (...)
self.conv = uu.Conv1d(...)
```
like the rest of the public modules.

**Comment by DouglasOrr** [comment]
Thank you for reporting this! I've prepared a fix, which should be able to go in soon.
